name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
